theme: jekyll-theme-hacker

lang: "it-IT"

plugins:
  - jekyll-sitemap

google_tracking_id: UA-222163131-1
google_ad_client: ca-pub-9278877935617832

collections:
  android:
    output: true
    order:
      - 1.1_android_studio
      - 1.2_first_project
      - 1.3_activity
      - 1.4_hello_world